## Aggregations
Aggreagtions just means summarizing values in your array into a single result -- like sums, means, counts, min, max. Its Numpy equivalent of statistics

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6])

#print(np.sum(data))
print(data.sum())

#print(np.min(data))
print(data.min())

#print(np.max(data))
print(data.max())

#print(np.mean(data))
print(data.mean())

#print(np.std(data))
print(data.std())

#print(np.var(data))
print(data.var())


21
1
6
3.5
1.707825127659933
2.9166666666666665


In [36]:
print(np.cumsum(data))
print(np.cumprod(data))

[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]


## Aggregation on 2D Arrays

In [37]:
twoD_Array = np.array([[1,2,3],
                            [4,5,6]])

print(np.sum(twoD_Array))   

# Sum along rows Axis=1

print(np.sum(twoD_Array, axis=1))

#Sum along columns Axis=0

print(np.sum(twoD_Array, axis =0))

21
[ 6 15]
[5 7 9]


## Aggregation on 3D Arrays

In [42]:
arr3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]

])
print(type(arr3d))
print(arr3d)
print(arr3d.shape)

print(np.sum(arr3d))
print(np.mean(arr3d))
print(np.max(arr3d))

<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
78
6.5
12


In [ ]:
#It can get really powerful

print(np.sum(arr3d, axis = 0))

print(np.sum(arr3d, axis = 1))

#when the axis=2 collapse across the columns inside each row
print(np.sum(arr3d, axis = 2))

[[ 8 10 12]
 [14 16 18]]
[[ 5  7  9]
 [17 19 21]]
[[ 6 15]
 [24 33]]


In [9]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
A.max(axis=0)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [7]:
A.min(axis=1)

array([1, 4, 7])