## BroadCasting
Broadcasting is Numpy's way of performing arithmetic operations on arrays of different shapes without explicitly replicating data.
This works by stretching the smaller array along dimensions so it can match the bigger one.
Instead of looping element, NumPy applies operations in a vectorized way.

#BroadCasting Rules
If the dimensions are equal => it is okay
if one dimension is 1 => it is stretched to match the other
if neither is 1 and they differ => incompatible

In [ ]:
import numpy as np

x = np.array([1,2,3])
y = 10

print(x+y)

#In the example above 10 is broadcasted to match the shape of x

[11 12 13]


In [ ]:
A = np.array([[1,2,3],
               [4,5,6]])

B = np.array([10,20,30])

print(A.shape)

print(A+B)

#The array that is incomplete is replicated to match the shape of the other array

(2, 3)
[[11 22 33]
 [14 25 36]]


In [6]:
#Column BroadCasting
A = np.array([[1,2,3],
              [4,5,6]])

C = np.array([[10],
                [20]])

print(A + C)                              

              


[[11 12 13]
 [24 25 26]]


In [9]:
#Row BroadCasting
A = np.array([[1,2,3],
               [4, 5, 6],
                [7,8,9]])

row = np.array([10,20,30])        
print(A+row)        


[[11 22 33]
 [14 25 36]
 [17 28 39]]
