## Importing Libraries

In [38]:
import numpy as np
from matplotlib import pyplot as plt

## Creating Numpy Arrays in Python

Create a 1D Array

In [2]:
#You can create a Numpy Array from a Python List
student_fare_prices_to_zindua = [150, 160, 110, 180, 130, 160, 250, 160]

student_fares_array = np.array(student_fare_prices_to_zindua)

print(student_fares_array)
print(type(student_fares_array))

[150 160 110 180 130 160 250 160]
<class 'numpy.ndarray'>


In [3]:
print(student_fare_prices_to_zindua)
print(type(student_fare_prices_to_zindua))

[150, 160, 110, 180, 130, 160, 250, 160]
<class 'list'>


Creating a 2D Numpy Array

In [4]:
combined_student_fares = [[20,25,30],
                           [40,50,60]]
roundtrip_fare_array = np.array(combined_student_fares)

print(combined_student_fares)

print(type(roundtrip_fare_array))

[[20, 25, 30], [40, 50, 60]]
<class 'numpy.ndarray'>


Creating a 3D Numpy Array

In [5]:
round_trip_student_fare1 = np.array([[20,25,30], [40,50,60]])
round_trip_student_fare2 =np.array([[20,25,30], [40,50,60]]) 
round_trip_student_fare3 =np.array([[20,25,30], [40,50,60]]) 

round_trip_3d_array = np.array([round_trip_student_fare1, round_trip_student_fare2, round_trip_student_fare3])

print(type(round_trip_3d_array))
print(round_trip_3d_array)



                   



<class 'numpy.ndarray'>
[[[20 25 30]
  [40 50 60]]

 [[20 25 30]
  [40 50 60]]

 [[20 25 30]
  [40 50 60]]]


## Creating Arrys from Scratch

- There are many Numpy Functions used to create arrays from scratch, including:
   -'np.zeros()'
   -'np.random().random()'
   -'np.arange()'

# Creating Arrays : np.zeros()

In [6]:
np.zeros((5,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Creating Arrays: np.random.random()

In [7]:
np.random.random((2,4)) # 2 rows and 4 columns of random numbers between o and 1

array([[0.97817072, 0.86742386, 0.18797028, 0.63974237],
       [0.46960578, 0.43871647, 0.66346606, 0.20202836]])

# Creating Arrays: np.arange()

In [8]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(-3, 0, 3)

array([-3])

## ShapeShifting
# Finding an array's Shape


In [10]:
zeros_array = np.zeros((3,5))
print(zeros_array)
zeros_array.shape

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(3, 5)

## Rows and Columns 
#  In 2d Array:
   Rows are the fisrt Dimension
   Columns are the second dimension

## Flattening an Array
 - This is just converting an array to be a 3D array.

In [11]:
twoD_array = np.array([[1,2],[4,5],[6,7]])
print(twoD_array)

[[1 2]
 [4 5]
 [6 7]]


In [12]:
twoD_array.shape

(3, 2)

In [13]:
flattened_twoD_array = twoD_array.flatten()
print(flattened_twoD_array)

[1 2 4 5 6 7]


In [14]:
flattened_twoD_array.shape

(6,)

# Reshaping an array

In [15]:
twoD_array_one = np.array([[1,2],[4,5],[6,7]])
print(twoD_array_one)

[[1 2]
 [4 5]
 [6 7]]


In [16]:
twoD_array_one.shape

(3, 2)

In [17]:
reshaped_array = twoD_array_one.reshape(2,3)
print(reshaped_array)

[[1 2 4]
 [5 6 7]]


In [18]:
reshaped_array.shape

(2, 3)

# Rules During Reshaping

In [19]:
reshaped_array_error = twoD_array_one.reshape(1,6)
print(reshaped_array_error)

[[1 2 4 5 6 7]]


## Indexing and Slicing of Arrays

In [20]:
sodoku_game = np.array([[9,10,11,12,8],
                        [6,7,8,9,4],
                        [3,2,1,0,1]])
print(sodoku_game)

#Indexing row 1 and row 2
indexing_array = sodoku_game[1,3]
print(indexing_array)

#Indexing a single column in a 2D array
print_column_array = sodoku_game[:, 3]
print(print_column_array)

#Indexing a single row in a 2D array
print_row_array = sodoku_game[1]
print(print_row_array)

[[ 9 10 11 12  8]
 [ 6  7  8  9  4]
 [ 3  2  1  0  1]]
9
[12  9  0]
[6 7 8 9 4]


## Slicing Element in an Array

In [21]:
#Slicing a 1D Arrays
OneD_Array_Two = np.array([2,4,6,8,10])

print(OneD_Array_Two[2:4])

[6 8]


In [22]:
#Slicing 2D Arrays
my_sodoku_game_two = np.array([[9,10,11,12,8],
                                [6,7,8,9,4],
                                  [3,2,1,0,1]])

print(my_sodoku_game_two)

print(my_sodoku_game_two[1:3,2:4])

[[ 9 10 11 12  8]
 [ 6  7  8  9  4]
 [ 3  2  1  0  1]]
[[8 9]
 [1 0]]


In [23]:
#Slicing with a Step Size
print(my_sodoku_game_two[1:3, 1:4:2])

[[7 9]
 [2 0]]


# Creating copies of Arrays

In [24]:
array = np.array([[99, 55, 2, 4],
                  [7, 6, 8, 8],
                  [1, 6, 7, 7]])

print(array)
#copy() just creates another array
x2_sub_copy = array[:2, :2].copy()
print(x2_sub_copy)

[[99 55  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99 55]
 [ 7  6]]


In [25]:
#If we now modify this subarray, the original array is not touched
#You can modify the array by replacing the value 
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42 55]
 [ 7  6]]


## Array Concatenation and Splitting
It is also possible to concatenate and split arrays

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
#Concatenate along the second axis(zero indexed)
#when axis = 1 is known as horizontal stacking
np.concatenate([grid, grid], axis=1)

#when axis = 0 its known as vertical satacking


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [29]:
#When working with arrays of mixed dimensions, it can be clear to use the np.vstack(vertical stack) and np.hpstack(horizontal stack)

x= np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [30]:
#Stacking rule, the number of rows must match especially when doing it horizontally
y = np.array([[4],
               [7]])
grid1 = np.array([[12, 3, 6],
                 [34, 56, 78]
                 ])

np.hstack([y, grid1])


array([[ 4, 12,  3,  6],
       [ 7, 34, 56, 78]])

## Splitting of Arrays 
The opposite of concetenation is splitting which is implemented by np.split, np.hsplit and np.vpsplit

In [31]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 =  np.split(x, [3, 5])
print( x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [32]:
# N splits-points leads to N+1 subarrays. The related functions np.hspliy and np.vsplit are similar to the ones we talked about above
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
#The vsplit splits the array to the upper part and to the lower part with an axis = 2
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
#The hsplit splits the array to the left and to the right part with an axis
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Filtering Arrays
There are two ways to filter arrays

1. Masks and Fancy Indexing.
2. Using np.where()

In [35]:
# Boolean Masks
one_to_five =  np.arange(1,11)
one_to_five



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
#Defining my mask

mask = one_to_five % 2 == 0
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

Filtering with Fancy Indexing

In [37]:
#Fancy Indexing
one_to_twenty = np.arange(1,21)
print(one_to_twenty)

mask1 = one_to_twenty % 5 == 0
one_to_twenty[mask]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


IndexError: boolean index did not match indexed array along axis 0; size of axis is 20 but size of corresponding boolean axis is 10

# 2D Fancy Indexing

In [ ]:
class_cohort_and_num_of_students = np.array([[25,9], [24, 5],[23, 6], [22, 15]])
class_cohort_and_num_of_students

In [ ]:
mask = class_cohort_and_num_of_students[:, 1] > 7
print(mask)
class_cohort_and_num_of_students[mask]

# Filtering using the np.where()

In [ ]:
np.where(class_cohort_and_num_of_students[:, 1] < 10)


In [ ]:
#Using the 'np.where()' find all elements equals 5 and replace with 6
np.where(one_to_twenty == 5, 6, one_to_twenty)

In [ ]:
#Using the 'np.where()' in a 2d array find all elements equals 5 and replace it with 6
np.where(class_cohort_and_num_of_students == 5, 6, class_cohort_and_num_of_students)

## Adding and Removing Data 

In [ ]:
new_cohort = np.array([[26, 11], [27,13]])

## Using 'np.arange' with 'matplotlib' in coming up with visualization or defining the visualization 

In [ ]:
plt.scatter(np.arange(0,7),
            np.arange(-3,4))

plt.show()