## Universal Functions
Universal functions are functions in Numpy that operate element-wise on arrays.
They are vectorize- meaning they avoid Python loops and run much faster
They work on scalars, 1Darrays, 2D arrays and higher dimensions automatically.
There are several types of ufuncs:

In [5]:
# Unary ufuncs

import numpy as np

x= np.array([1, 2, 3, 4])
print(np.sqrt(x))
print(np.exp(x))
print(np.sin(x))
print(np.abs([-1, -2, 3]))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[1 2 3]


In [3]:
# Binary ufuncs
a =  np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


# Advantages of ufuncs
Speed: Avoids python loops, executes at C-speed
Broadcasting: Automatically applies operations on arrays of different shapes.
Flexibility: Many ufuncs allow specifying out arrays and where conditions

# Triginometric Ufuncs


In [9]:
Beta = np.array([0, np.pi/2, np.pi])
print(np.sin(Beta))
print(np.cos(Beta))
print(np.tan(Beta))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# Logarithms and Exponential ufuncs

In [14]:
x = np.array([1, 2, 3, 4, 5])
print(np.log(x))
print(np.log2(x))
print(np.exp2(x))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[ 2.  4.  8. 16. 32.]


# Advanced Ufuncs


In [ ]:
#The out argument prints the output array in another array
A = np.arange(5)
B = np.zeros(10)

print(A)
np.power(2, A, out=B[: : 2])
print(B)

[0 1 2 3 4]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


# Other Ufuncs

In [30]:
x = np.arange(1, 6)
Multiplication_table = np.multiply.outer(x, x)
print(Multiplication_table)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
